Сделал историю без ограничений и избавился от повторных просмотров истории,сохраняя последний просмотр
chunkychunk2/sprint_6-solution pull request #1
Opened 2024-11-24 23:23 UTC by chunkychunk2

Усовершенствовал юнит тесты

2024-11-25 21:18 UTC, Yang-Pi commented on src/main/java/com/yandex/taskmanager/HistoryManager.java
> +public interface HistoryManager {
HistoryManager также должен содержать метод remove(id)

2024-11-25 21:20 UTC, Yang-Pi commented on src/main/java/com/yandex/taskmanager/service/InMemoryHistoryManager.java
> +public class InMemoryHistoryManager implements HistoryManager {
В рамках класса InMemoryHistoryManager должны быть реализованы методы linkLast, getTasks, removeNode

2024-11-25 21:22 UTC, Yang-Pi commented on src/main/java/com/yandex/taskmanager/service/InMemoryHistoryManager.java
> +        return new LinkedList<>(HISTORY.values());
Метод history() должен возвращать ArrayList. Суть всей задачи в том, чтобы самостоятельно реализовать связный список и понять как он работает, как устроены ссылки на начало и конец) А не использовать готовые решения стандартной библиотеки

2024-11-25 21:23 UTC, Yang-Pi requested changes
нужно реализовать свой вариант связного списка)

2024-11-26 11:44 UTC, chunkychunk2 commented on src/main/java/com/yandex/taskmanager/HistoryManager.java
> +public interface HistoryManager {
Добавил

2024-11-26 11:44 UTC, chunkychunk2 commented on src/main/java/com/yandex/taskmanager/service/InMemoryHistoryManager.java
> +public class InMemoryHistoryManager implements HistoryManager {
Реализовал

2024-11-26 11:44 UTC, chunkychunk2 commented on src/main/java/com/yandex/taskmanager/service/InMemoryHistoryManager.java
> +        return new LinkedList<>(HISTORY.values());
Реализовал связанный список в классе Node

2024-11-26 16:08 UTC, Yang-Pi commented on src/test/java/TaskTest.java
> +    void orderTest() {
Осталось написать несколько тестов, подтверждающих работу истории (можно написать как в Main, так и как @Test):

- удалите задачу, которая есть в истории, и проверьте, что при печати она не будет выводиться;
- удалите эпик с тремя подзадачами и убедитесь, что из истории удалился как сам эпик, так и все его подзадачи.

2024-11-26 16:08 UTC, Yang-Pi reviewed
Отличная работа! Хорошая реализация с пустой головой и хвостом. Осталось написать несколько тестов

2024-11-26 20:05 UTC, chunkychunk2 commented on src/test/java/TaskTest.java
> +    void orderTest() {
Добавил тесты, не была реализована логика удаления тасок из истории, добавил логику в последнем пуше

2024-11-27 19:05 UTC, Yang-Pi approved these changes

2024-11-28 14:45 UTC, merged